title: Site
sections:
  pages:
    headline: Main Pages
    create: false
    templates:
      - projects
      - info
    status: all
    layout: cards
    size: large
    image:
      back: black
      cover: false
